name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b #v5.4.0
        with:
          go-version-file: go.mod
      - name: Initialize CodeQL
        uses: github/codeql-action/init@60168efe1c415ce0f5521ea06d5c2062adbeed1b #v3.28.17
        with:
          languages: go
      - name: Setup Mockgen
        run: go install go.uber.org/mock/mockgen@latest
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@60168efe1c415ce0f5521ea06d5c2062adbeed1b #v3.28.17
      - name: Run tests
        run: |
          go generate github.com/lonegunmanb/tflintenv/...
          go test -v github.com/lonegunmanb/tflintenv/...
      - name: golangci-lint
        run: |
          docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v2.1.6-alpine golangci-lint run -v --timeout=3600s
      - name: Run Gosec Security Scanner
        uses: securego/gosec@955a68d0d19f4afb7503068f95059f7d0c529017 #v2.22.3